spring.application.name=backend

# KET NOI CLOUD DATABASE (AIVEN)
spring.datasource.url=jdbc:mysql://mysql-task-automation-task-automation-db.f.aivencloud.com:14862/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true